const cars = [
  {
    image: "./media/car1.png",
    name: "Audi",
    type: "SUV",
    category: "Standard",
    persons: 5,
    suitcases: 4,
    price: 800,
  },
  {
    image: "./media/car2.png",
    name: "Volkswagen",
    type: "Hatchpack",
    category: "Standard",
    persons: 4,
    suitcases: 3,
    price: 650,
  },
  {
    image: "./media/car3.png",
    name: "Mustang",
    type: "Sport",
    category: "Standard",
    persons: 4,
    suitcases: 3,
    price: 1200,
  },
  {
    image: "./media/car4.png",
    name: "Opel",
    type: "Van",
    category: "Van",
    persons: 9,
    suitcases: 6,
    price: 1240,
  },
  {
    image: "./media/car5.png",
    name: "Cadillac",
    type: "Limousine",
    category: "Limousine",
    persons: 9,
    suitcases: 5,
    price: 2242,
  },
];
